--DROP VIEW XXMKT.XXMKT_SEQUENCES#;

/* Formatted on 7/28/2020 1:18:49 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE EDITIONING VIEW XXMKT.XXMKT_SEQUENCES#
(
   SEQ_TYPE_ID,
   APPLICATION_SHORT_NAME,
   SEQ_TYPE,
   CURRENT_MONTH,
   CURRENT_YEAR,
   LAST_VALUE,
   ENABLED_FLAG,
   DESCRIPTION,
   ORG_ID,
   CURRENT_FULL_DATE,
   CREATED_BY,
   CREATION_DATE,
   LAST_UPDATED_BY,
   LAST_UPDATE_DATE,
   LAST_UPDATE_LOGIN,
   CURRENT_DAY
)
AS
   SELECT SEQ_TYPE_ID SEQ_TYPE_ID,
          APPLICATION_SHORT_NAME APPLICATION_SHORT_NAME,
          SEQ_TYPE SEQ_TYPE,
          CURRENT_MONTH CURRENT_MONTH,
          CURRENT_YEAR CURRENT_YEAR,
          LAST_VALUE LAST_VALUE,
          ENABLED_FLAG ENABLED_FLAG,
          DESCRIPTION DESCRIPTION,
          ORG_ID ORG_ID,
          CURRENT_FULL_DATE CURRENT_FULL_DATE,
          CREATED_BY CREATED_BY,
          CREATION_DATE CREATION_DATE,
          LAST_UPDATED_BY LAST_UPDATED_BY,
          LAST_UPDATE_DATE LAST_UPDATE_DATE,
          LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
          CURRENT_DAY CURRENT_DAY
     FROM "XXMKT"."XXMKT_SEQUENCES";


CREATE OR REPLACE SYNONYM APPS.XXMKT_SEQUENCES FOR XXMKT.XXMKT_SEQUENCES#;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, READ, DEBUG ON XXMKT.XXMKT_SEQUENCES# TO APPS WITH GRANT OPTION;
