DROP TABLE XXMKT.XXMKT_FA_RETIREMENT CASCADE CONSTRAINTS;

CREATE TABLE XXMKT.XXMKT_FA_RETIREMENT
(
  BOOK_TYPE_CODE       VARCHAR2(15 BYTE),
  SERIAL_NUMBER        VARCHAR2(35 BYTE),
  COST_RETIRED         NUMBER,
  RETIREMENT_DATE      DATE,
  COST_OF_REMOVAL      NUMBER,
  RETIREMENT_TYPE      VARCHAR2(15 BYTE),
  CUSTOMER_ID          NUMBER,
  PROCEEDS_OF_SALE     NUMBER,
  DESCRIPTION          VARCHAR2(240 BYTE),
  REQUEST_ID           NUMBER,
  ASSET_ID             NUMBER,
  PARTY_ID             NUMBER,
  BILL_SITE_USE_ID     NUMBER,
  PAYMENT_TERM_ID      NUMBER,
  TRX_SOURCE_ID        NUMBER,
  TRX_TYPE_ID          NUMBER,
  CUSTOMER_TRX_ID      NUMBER,
  STATUS               VARCHAR2(20 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  GROUP_ID             NUMBER,
  COMMENTS             VARCHAR2(30 BYTE),
  SOLD_TO              VARCHAR2(30 BYTE),
  INVOICE_GROUP        VARCHAR2(150 BYTE),
  CODE_COMBINATION_ID  NUMBER,
  CREATED_BY           NUMBER                   DEFAULT -1,
  LAST_UPDATED_BY      NUMBER                   DEFAULT -1,
  CREATION_DATE        DATE                     DEFAULT sysdate,
  LAST_UPDATE_DATE     DATE                     DEFAULT sysdate,
  LAST_UPDATE_LOGIN    NUMBER                   DEFAULT -1
)
TABLESPACE XXMKTD
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXMKT.XXMKT_FA_RETIREMENT TO APPS WITH GRANT OPTION;
