DROP VIEW XXMKT.XXMKT_FA_ADDITION#;

/* Formatted on 7/28/2020 2:16:46 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE EDITIONING VIEW XXMKT.XXMKT_FA_ADDITION#
(
   BOOK_TYPE_CODE,
   DESCRIPTION,
   ASSET_CATEGORY_ID,
   UNIT,
   LOCATION_ID,
   COST,
   DATE_PLACE_IN_SERVICE,
   DEPRE_CCID,
   ASSET_TYPE,
   SERIAL_NUMBER,
   ASSET_ID,
   REQUEST_ID,
   MASS_ADDITION_ID,
   MASSADD_DIST_ID,
   STATUS,
   ERROR_MESSAGE,
   INVOICE_NUMBER,
   INVOICE_ID,
   VENDOR_NUMBER,
   INVOICE_DATE,
   GROUP_ID,
   VENDOR_ID,
   PO_NUMBER,
   CREATED_BY,
   LAST_UPDATED_BY,
   LAST_UPDATE_LOGIN,
   CREATION_DATE,
   LAST_UPDATE_DATE
)
AS
   SELECT BOOK_TYPE_CODE BOOK_TYPE_CODE,
          DESCRIPTION DESCRIPTION,
          ASSET_CATEGORY_ID ASSET_CATEGORY_ID,
          UNIT UNIT,
          LOCATION_ID LOCATION_ID,
          COST COST,
          DATE_PLACE_IN_SERVICE DATE_PLACE_IN_SERVICE,
          DEPRE_CCID DEPRE_CCID,
          ASSET_TYPE ASSET_TYPE,
          SERIAL_NUMBER SERIAL_NUMBER,
          ASSET_ID ASSET_ID,
          REQUEST_ID REQUEST_ID,
          MASS_ADDITION_ID MASS_ADDITION_ID,
          MASSADD_DIST_ID MASSADD_DIST_ID,
          STATUS STATUS,
          ERROR_MESSAGE ERROR_MESSAGE,
          INVOICE_NUMBER INVOICE_NUMBER,
          INVOICE_ID INVOICE_ID,
          VENDOR_NUMBER VENDOR_NUMBER,
          INVOICE_DATE INVOICE_DATE,
          GROUP_ID GROUP_ID,
          VENDOR_ID VENDOR_ID,
          PO_NUMBER PO_NUMBER,
          CREATED_BY CREATED_BY,
          LAST_UPDATED_BY LAST_UPDATED_BY,
          LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
          CREATION_DATE CREATION_DATE,
          LAST_UPDATE_DATE LAST_UPDATE_DATE
     FROM "XXMKT"."XXMKT_FA_ADDITION";


CREATE OR REPLACE SYNONYM APPS.XXMKT_FA_ADDITION FOR XXMKT.XXMKT_FA_ADDITION#;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, READ, DEBUG ON XXMKT.XXMKT_FA_ADDITION# TO APPS WITH GRANT OPTION;
