--DROP TABLE XXMKT.XXMKT_FA_ADDITION CASCADE CONSTRAINTS;

CREATE TABLE XXMKT.XXMKT_FA_ADDITION
(
  BOOK_TYPE_CODE         VARCHAR2(15 BYTE),
  DESCRIPTION            VARCHAR2(240 BYTE),
  ASSET_CATEGORY_ID      NUMBER,
  UNIT                   NUMBER,
  LOCATION_ID            NUMBER,
  COST                   NUMBER,
  DATE_PLACE_IN_SERVICE  DATE,
  DEPRE_CCID             NUMBER,
  ASSET_TYPE             VARCHAR2(15 BYTE),
  SERIAL_NUMBER          VARCHAR2(35 BYTE),
  ASSET_ID               NUMBER,
  REQUEST_ID             NUMBER,
  MASS_ADDITION_ID       NUMBER,
  MASSADD_DIST_ID        NUMBER,
  STATUS                 VARCHAR2(20 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  INVOICE_NUMBER         VARCHAR2(50 BYTE),
  INVOICE_ID             NUMBER,
  VENDOR_NUMBER          VARCHAR2(30 BYTE),
  INVOICE_DATE           DATE,
  GROUP_ID               NUMBER,
  VENDOR_ID              NUMBER,
  PO_NUMBER              VARCHAR2(240 BYTE),
  CREATED_BY             NUMBER                 DEFAULT -1,
  LAST_UPDATED_BY        NUMBER                 DEFAULT -1,
  LAST_UPDATE_LOGIN      NUMBER                 DEFAULT -1,
  CREATION_DATE          DATE                   DEFAULT sysdate,
  LAST_UPDATE_DATE       DATE                   DEFAULT sysdate
)
TABLESPACE XXMKTD
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXMKT.XXMKT_FA_ADDITION TO APPS WITH GRANT OPTION;
