CREATE OR REPLACE FORCE EDITIONING VIEW XXMKT.XXMKT_TEST_FILES#
(
   PL_ID,
   PL_NAME,
   PL_FILE
)
AS
   SELECT PL_ID PL_ID, PL_NAME PL_NAME, PL_FILE PL_FILE
     FROM "XXMKT"."XXMKT_TEST_FILES";


CREATE OR REPLACE SYNONYM APPS.XXMKT_TEST_FILES FOR XXMKT.XXMKT_TEST_FILES#;
