--DROP SEQUENCE XXMKT.XXMKT_SEQUENCES_S;

CREATE SEQUENCE XXMKT.XXMKT_SEQUENCES_S
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


CREATE OR REPLACE SYNONYM APPS.XXMKT_SEQUENCES_S FOR XXMKT.XXMKT_SEQUENCES_S;


GRANT ALTER, SELECT ON XXMKT.XXMKT_SEQUENCES_S TO APPS;
