--ALTER TABLE XXMKT.XXMKT_SEQUENCES
-- DROP PRIMARY KEY CASCADE;
--
--DROP TABLE XXMKT.XXMKT_SEQUENCES CASCADE CONSTRAINTS;

CREATE TABLE XXMKT.XXMKT_SEQUENCES
(
  SEQ_TYPE_ID             NUMBER                NOT NULL,
  APPLICATION_SHORT_NAME  VARCHAR2(50 BYTE)     NOT NULL,
  SEQ_TYPE                VARCHAR2(30 BYTE)     NOT NULL,
  CURRENT_MONTH           VARCHAR2(2 BYTE),
  CURRENT_YEAR            NUMBER,
  LAST_VALUE              NUMBER,
  ENABLED_FLAG            VARCHAR2(1 BYTE)      DEFAULT 'Y'                   NOT NULL,
  DESCRIPTION             VARCHAR2(150 BYTE),
  ORG_ID                  NUMBER                NOT NULL,
  CURRENT_FULL_DATE       DATE,
  CREATED_BY              NUMBER                DEFAULT -1                    NOT NULL,
  CREATION_DATE           DATE                  DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATED_BY         NUMBER                DEFAULT -1                    NOT NULL,
  LAST_UPDATE_DATE        DATE                  DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATE_LOGIN       NUMBER                DEFAULT -1                    NOT NULL,
  CURRENT_DAY             VARCHAR2(2 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX XXMKT.XXMKT_SEQUENCES_PK ON XXMKT.XXMKT_SEQUENCES
(SEQ_TYPE_ID)
LOGGING
TABLESPACE XXMKTX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX XXMKT.XXMKT_SEQUENCES_U1 ON XXMKT.XXMKT_SEQUENCES
(ORG_ID, ENABLED_FLAG, APPLICATION_SHORT_NAME, SEQ_TYPE, CURRENT_DAY, 
CURRENT_MONTH, CURRENT_YEAR, CURRENT_FULL_DATE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE XXMKT.XXMKT_SEQUENCES ADD (
  CONSTRAINT XXMKT_SEQUENCES_PK
  PRIMARY KEY
  (SEQ_TYPE_ID)
  USING INDEX XXMKT.XXMKT_SEQUENCES_PK
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXMKT.XXMKT_SEQUENCES TO APPS WITH GRANT OPTION;
