DROP TABLE XXSHP.XXSHP_INV_ITEM_CATS_STG CASCADE CONSTRAINTS;

CREATE TABLE XXSHP.XXSHP_INV_ITEM_CATS_STG
(
  FILE_ID            NUMBER,
  FILE_NAME          VARCHAR2(100 BYTE),
  ORG_CODE           VARCHAR2(3 BYTE),
  ITEM_CODE          VARCHAR2(20 BYTE),
  CATEGORY_SET_NAME  VARCHAR2(40 BYTE),
  SEGMENT1           VARCHAR2(50 BYTE),
  SEGMENT2           VARCHAR2(50 BYTE),
  SEGMENT3           VARCHAR2(50 BYTE),
  SEGMENT4           VARCHAR2(50 BYTE),
  SEGMENT5           VARCHAR2(50 BYTE),
  SEGMENT6           VARCHAR2(50 BYTE),
  STATUS             VARCHAR2(20 BYTE),
  FLAG               VARCHAR2(1 BYTE),
  ERROR_MESSAGE      VARCHAR2(2500 BYTE),
  CREATED_BY         NUMBER                     DEFAULT -1,
  CREATION_DATE      DATE                       DEFAULT SYSDATE,
  LAST_UPDATED_BY    NUMBER                     DEFAULT -1,
  LAST_UPDATE_DATE   DATE                       DEFAULT SYSDATE,
  LAST_UPDATE_LOGIN  NUMBER                     DEFAULT -1
)
TABLESPACE XXSHPD
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM APPS.XXSHP_INV_ITEM_CATS_STG FOR XXSHP.XXSHP_INV_ITEM_CATS_STG;
