--DROP TABLE XXKHD.XXKHD_FA_MUTATION CASCADE CONSTRAINTS;

CREATE TABLE XXKHD.XXKHD_FA_MUTATION
(
  BOOK_TYPE_CODE         VARCHAR2(15 BYTE),
  SERIAL_NUMBER          VARCHAR2(35 BYTE),
  DEPRE_CCID             NUMBER,
  LOCATION_ID            NUMBER,
  REQUEST_ID             NUMBER,
  ASSET_ID               NUMBER,
  TRANSACTION_HEADER_ID  NUMBER,
  STATUS                 VARCHAR2(20 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  GROUP_ID               NUMBER,
  CREATED_BY             NUMBER                 DEFAULT -1,
  LAST_UPDATED_BY        NUMBER                 DEFAULT -1,
  LAST_UPDATE_LOGIN      NUMBER                 DEFAULT -1,
  CREATION_DATE          DATE                   DEFAULT sysdate,
  LAST_UPDATE_DATE       DATE                   DEFAULT sysdate
)
TABLESPACE XXKHDD
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXKHD.XXKHD_FA_MUTATION TO APPS WITH GRANT OPTION;
