DROP VIEW XXKHD.XXKHD_FA_RETIREMENT#;

/* Formatted on 7/28/2020 2:18:52 PM (QP5 v5.256.13226.35538) */
CREATE OR REPLACE FORCE EDITIONING VIEW XXKHD.XXKHD_FA_RETIREMENT#
(
   BOOK_TYPE_CODE,
   SERIAL_NUMBER,
   COST_RETIRED,
   RETIREMENT_DATE,
   COST_OF_REMOVAL,
   RETIREMENT_TYPE,
   CUSTOMER_ID,
   PROCEEDS_OF_SALE,
   DESCRIPTION,
   REQUEST_ID,
   ASSET_ID,
   PARTY_ID,
   BILL_SITE_USE_ID,
   PAYMENT_TERM_ID,
   TRX_SOURCE_ID,
   TRX_TYPE_ID,
   CUSTOMER_TRX_ID,
   STATUS,
   ERROR_MESSAGE,
   GROUP_ID,
   COMMENTS,
   SOLD_TO,
   INVOICE_GROUP,
   CODE_COMBINATION_ID,
   CREATED_BY,
   LAST_UPDATED_BY,
   CREATION_DATE,
   LAST_UPDATE_DATE,
   LAST_UPDATE_LOGIN
)
AS
   SELECT BOOK_TYPE_CODE BOOK_TYPE_CODE,
          SERIAL_NUMBER SERIAL_NUMBER,
          COST_RETIRED COST_RETIRED,
          RETIREMENT_DATE RETIREMENT_DATE,
          COST_OF_REMOVAL COST_OF_REMOVAL,
          RETIREMENT_TYPE RETIREMENT_TYPE,
          CUSTOMER_ID CUSTOMER_ID,
          PROCEEDS_OF_SALE PROCEEDS_OF_SALE,
          DESCRIPTION DESCRIPTION,
          REQUEST_ID REQUEST_ID,
          ASSET_ID ASSET_ID,
          PARTY_ID PARTY_ID,
          BILL_SITE_USE_ID BILL_SITE_USE_ID,
          PAYMENT_TERM_ID PAYMENT_TERM_ID,
          TRX_SOURCE_ID TRX_SOURCE_ID,
          TRX_TYPE_ID TRX_TYPE_ID,
          CUSTOMER_TRX_ID CUSTOMER_TRX_ID,
          STATUS STATUS,
          ERROR_MESSAGE ERROR_MESSAGE,
          GROUP_ID GROUP_ID,
          COMMENTS COMMENTS,
          SOLD_TO SOLD_TO,
          INVOICE_GROUP INVOICE_GROUP,
          CODE_COMBINATION_ID CODE_COMBINATION_ID,
          CREATED_BY CREATED_BY,
          LAST_UPDATED_BY LAST_UPDATED_BY,
          CREATION_DATE CREATION_DATE,
          LAST_UPDATE_DATE LAST_UPDATE_DATE,
          LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN
     FROM "XXKHD"."XXKHD_FA_RETIREMENT";


CREATE OR REPLACE SYNONYM APPS.XXKHD_FA_RETIREMENT FOR XXKHD.XXKHD_FA_RETIREMENT#;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, READ, DEBUG ON XXKHD.XXKHD_FA_RETIREMENT# TO APPS WITH GRANT OPTION;
