CREATE OR REPLACE FORCE EDITIONING VIEW XXKHD.XXKHD_TEST_FILES#
(
   PL_ID,
   PL_NAME,
   PL_FILE
)
AS
   SELECT PL_ID PL_ID, PL_NAME PL_NAME, PL_FILE PL_FILE
     FROM "XXKHD"."XXKHD_TEST_FILES";


CREATE OR REPLACE SYNONYM APPS.XXKHD_TEST_FILES FOR XXKHD.XXKHD_TEST_FILES#;
