--DROP TABLE XXKHD.XXKHD_FA_SERIAL_NUM_STG CASCADE CONSTRAINTS;

CREATE TABLE XXKHD.XXKHD_FA_SERIAL_NUM_STG
(
  BOOK_TYPE_CODE               VARCHAR2(15 BYTE),
  EXPENSE_CODE_COMBINATION_ID  NUMBER,
  VENDOR_ID                    NUMBER,
  PO_NUMBER                    VARCHAR2(20 BYTE),
  RECEIPT_NUMBER               VARCHAR2(30 BYTE),
  RECEIPT_DATE                 DATE,
  PO_LINE                      NUMBER,
  DESCRIPTION                  VARCHAR2(240 BYTE),
  ASSET_CATEGORY_ID            NUMBER,
  FIXED_ASSETS_UNITS           NUMBER,
  LOCATION_ID                  NUMBER,
  FIXED_ASSETS_COST            NUMBER,
  DATE_PLACED_IN_SERVICE       DATE,
  SERIAL_NUMBER                VARCHAR2(35 BYTE),
  REQUEST_ID                   NUMBER,
  STATUS                       VARCHAR2(1 BYTE) DEFAULT 'N',
  ERROR_MESSAGE                VARCHAR2(4000 BYTE),
  CREATED_BY                   NUMBER           DEFAULT -1                    NOT NULL,
  CREATION_DATE                DATE             DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATED_BY              NUMBER           DEFAULT -1                    NOT NULL,
  LAST_UPDATE_DATE             DATE             DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATE_LOGIN            NUMBER           DEFAULT -1                    NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX XXKHD.XXKHD_FA_SERIAL_NUM_STG_N1 ON XXKHD.XXKHD_FA_SERIAL_NUM_STG
(STATUS)
LOGGING
TABLESPACE XXKHDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXKHD.XXKHD_FA_SERIAL_NUM_STG TO APPS WITH GRANT OPTION;
