/* Formatted on 1/8/2021 1:14:13 PM (QP5 v5.256.13226.35538) */
DROP TABLE XXKBN.XXKBN_RFP_INVOICE_HDR CASCADE CONSTRAINTS;

CREATE TABLE XXKBN.XXKBN_RFP_INVOICE_HDR
(
   INVOICE_ID                 NUMBER,
   INVOICE_NUM                VARCHAR2 (100 BYTE),
   INVOICE_TYPE_LOOKUP_CODE   VARCHAR2 (100 BYTE),
   INVOICE_DATE               DATE,
   VENDOR_ID                  NUMBER,
   VENDOR_NAME                VARCHAR2 (100 BYTE),
   VENDOR_SITE_ID             NUMBER,
   VENDOR_SITE_CODE           VARCHAR2 (100 BYTE),
   INVOICE_AMOUNT             NUMBER,
   INVOICE_CURRENCY_CODE      VARCHAR2 (50 BYTE),
   TERMS_NAME                 VARCHAR2 (100 BYTE),
   DESCRIPTION                VARCHAR2 (250 BYTE),
   SOURCE                     VARCHAR2 (50 BYTE),
   GROUP_ID                   VARCHAR2 (100 BYTE),
   GL_DATE                    DATE,
   ORG_ID                     NUMBER,
   ORG_CODE                   VARCHAR2 (10 BYTE),
   TERMS_DATE                 VARCHAR2 (100 BYTE),
   ATTRIBUTE1                 VARCHAR2 (250 BYTE),
   ATTRIBUTE2                 VARCHAR2 (250 BYTE),
   ATTRIBUTE3                 VARCHAR2 (250 BYTE),
   ATTRIBUTE4                 VARCHAR2 (250 BYTE),
   ATTRIBUTE5                 VARCHAR2 (250 BYTE),
   ATTRIBUTE6                 VARCHAR2 (250 BYTE),
   ATTRIBUTE7                 VARCHAR2 (250 BYTE),
   ATTRIBUTE8                 VARCHAR2 (250 BYTE),
   ATTRIBUTE9                 VARCHAR2 (250 BYTE),
   ATTRIBUTE10                VARCHAR2 (250 BYTE),
   ATTRIBUTE11                VARCHAR2 (250 BYTE),
   ATTRIBUTE12                VARCHAR2 (250 BYTE),
   ATTRIBUTE13                VARCHAR2 (250 BYTE),
   ATTRIBUTE14                VARCHAR2 (250 BYTE),
   ATTRIBUTE15                VARCHAR2 (250 BYTE),
   ERROR_MSG                  VARCHAR2 (500),
   FLAG_PROCESS               VARCHAR2 (1),
   CREATED_BY                 NUMBER DEFAULT -1,
   CREATION_DATE              DATE DEFAULT SYSDATE,
   LAST_UPDATED_BY            NUMBER DEFAULT -1,
   LAST_UPDATE_DATE           DATE DEFAULT SYSDATE,
   LAST_UPDATE_LOGIN          NUMBER DEFAULT -1
)
TABLESPACE XXKBND
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (MAXSIZE UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM APPS.XXKBN_RFP_INVOICE_HDR FOR XXKBN.XXKBN_RFP_INVOICE_HDR;