/* Formatted on 1/8/2021 4:07:13 PM (QP5 v5.256.13226.35538) */
DROP TABLE XXKBN.XXKBN_GL_JOURNAL_LINE CASCADE CONSTRAINTS;

CREATE TABLE XXKBN.XXKBN_GL_JOURNAL_LINE
(
   HEADER_ID             NUMBER,
   LINE_ID               NUMBER,
   LINE_NUM              NUMBER,
   LEDGER_ID             NUMBER,
   PERIOD_NAME           VARCHAR2 (250 BYTE),
   EFECTIVE_DATE         DATE,
   CODE_COMBINATION_ID   NUMBER,
   SEGMENT1              VARCHAR2 (250 BYTE),
   SEGMENT2              VARCHAR2 (250 BYTE),
   SEGMENT3              VARCHAR2 (250 BYTE),
   SEGMENT4              VARCHAR2 (250 BYTE),
   SEGMENT5              VARCHAR2 (250 BYTE),
   SEGMENT6              VARCHAR2 (250 BYTE),
   SEGMENT7              VARCHAR2 (250 BYTE),
   ENTERED_DR            NUMBER,
   ENTERED_CR            NUMBER,
   ACCOUNTED_DR          NUMBER,
   ACCOUNTED_CR          NUMBER,
   GROUP_ID              NUMBER,
   LINE_TYPE_CODE        VARCHAR2 (250 BYTE),
   REFERENCE1           VARCHAR2 (250 BYTE),
   REFERENCE4           VARCHAR2 (250 BYTE),
   REFERENCE10          VARCHAR2 (250 BYTE),
   REFERENCE25          VARCHAR2 (250 BYTE),
   REFERENCE26          VARCHAR2 (250 BYTE),
   REFERENCE27          VARCHAR2 (250 BYTE),
   REFERENCE28          VARCHAR2 (250 BYTE),
   REFERENCE29          VARCHAR2 (250 BYTE),
   REFERENCE30          VARCHAR2 (250 BYTE),
   ATTRIBUTE1            VARCHAR2 (250 BYTE),
   ATTRIBUTE2            VARCHAR2 (250 BYTE),
   ATTRIBUTE3            VARCHAR2 (250 BYTE),
   ATTRIBUTE4            VARCHAR2 (250 BYTE),
   ATTRIBUTE5            VARCHAR2 (250 BYTE),
   ATTRIBUTE6            VARCHAR2 (250 BYTE),
   ATTRIBUTE7            VARCHAR2 (250 BYTE),
   ATTRIBUTE8            VARCHAR2 (250 BYTE),
   ATTRIBUTE9            VARCHAR2 (250 BYTE),
   ATTRIBUTE10           VARCHAR2 (250 BYTE),
   ATTRIBUTE11           VARCHAR2 (250 BYTE),
   ATTRIBUTE12           VARCHAR2 (250 BYTE),
   ATTRIBUTE13           VARCHAR2 (250 BYTE),
   ATTRIBUTE14           VARCHAR2 (250 BYTE),
   ATTRIBUTE15           VARCHAR2 (250 BYTE),
   ERROR_MSG             VARCHAR2 (500),
   FLAG_PROCESS          VARCHAR2 (1),
   CREATED_BY            NUMBER DEFAULT -1,
   CREATION_DATE         DATE DEFAULT SYSDATE,
   LAST_UPDATED_BY       NUMBER DEFAULT -1,
   LAST_UPDATE_DATE      DATE DEFAULT SYSDATE,
   LAST_UPDATE_LOGIN     NUMBER DEFAULT -1
)
TABLESPACE XXKBND
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (MAXSIZE UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM APPS.XXKBN_GL_JOURNAL_LINE FOR XXKBN.XXKBN_GL_JOURNAL_LINE;