DROP TABLE XXKBN.XXKBN_GL_JOURNAL_LINE CASCADE CONSTRAINTS;

CREATE TABLE XXKBN.XXKBN_GL_JOURNAL_HDR
(
   HEADER_ID                    NUMBER,
   LEDGER_ID                    NUMBER,
   USER_JE_CATEGORY_NAME        VARCHAR2 (250 BYTE),
   USER_JE_SOURCE_NAME          VARCHAR2 (250 BYTE),
   CURRENCY_CODE                VARCHAR2 (25 BYTE),
   ACCOUNTING_DATE              DATE,
   DATE_CREATED                 DATE,
   ACTUAL_FLAG                  VARCHAR2 (1),
   JE_BATCH_ID                  NUMBER,
   JE_HEADER_ID                 NUMBER,
   RUNNING_TOTAL_DR             NUMBER,
   RUNNING_TOTAL_CR             NUMBER,
   RUNNING_TOTAL_ACCOUNTED_DR   NUMBER,
   RUNNING_TOTAL_ACCOUNTED_CR   NUMBER,
   CURRENCY_CONVERSION_RATE     NUMBER,
   CURRENCY_CONVERSION_DATE     DATE,
   ERROR_MSG                    VARCHAR2 (500),
   FLAG_PROCESS                 VARCHAR2 (1),
   CREATED_BY                   NUMBER DEFAULT -1,
   CREATION_DATE                DATE DEFAULT SYSDATE,
   LAST_UPDATED_BY              NUMBER DEFAULT -1,
   LAST_UPDATE_DATE             DATE DEFAULT SYSDATE,
   LAST_UPDATE_LOGIN            NUMBER DEFAULT -1
)
TABLESPACE XXKBND
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (MAXSIZE UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM APPS.XXKBN_GL_JOURNAL_HDR FOR XXKBN.XXKBN_GL_JOURNAL_HDR;