CREATE OR REPLACE VIEW XXVMT_GL_CODE_DESCRIPTION_V
AS
  SELECT GLCC.CODE_COMBINATION_ID,
         FLEX.DESCRIPTION,
         FLEX.FLEX_VALUE_MEANING,
         FLEX.SEGMENT_NUM
    FROM GL.GL_CODE_COMBINATIONS GLCC,
         (SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT1
                 AND VL.SEGMENT_NUM = 1
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 2
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 3
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 4
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 5
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 6
          UNION
          SELECT FVL.DESCRIPTION, FVL.FLEX_VALUE_MEANING, VL.SEGMENT_NUM
            FROM FND_ID_FLEX_STRUCTURES_TL TL,
                 FND_ID_FLEX_SEGMENTS_VL VL,
                 FND_FLEX_VALUES_VL FVL
           WHERE     TL.ID_FLEX_STRUCTURE_NAME = 'CRM_OPERATIONS_ACC_FLEXFIELD'
                 AND TL.ID_FLEX_NUM = VL.ID_FLEX_NUM
                 AND TL.ID_FLEX_CODE = VL.ID_FLEX_CODE
                 AND VL.FLEX_VALUE_SET_ID = FVL.FLEX_VALUE_SET_ID
                 AND TL.ID_FLEX_CODE = 'GL#'
                 --AND FVL.FLEX_VALUE_MEANING = GLCC.SEGMENT2
                 AND VL.SEGMENT_NUM = 7) FLEX
   WHERE     1 = 1
         AND (   FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT1
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT2
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT3
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT4
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT5
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT6
              OR FLEX.FLEX_VALUE_MEANING = GLCC.SEGMENT7)
ORDER BY SEGMENT_NUM

